Build detection content for Defense Evasion : Modify Authentication P…
dnif/content pull request #174
Opened 2023-03-09 11:48 UTC by Avni3

2023-07-26 09:37 UTC, aman1808 requested changes

2023-07-26 09:37 UTC, aman1808 commented on workbooks/Advanced Threat Detection/IAM Monitoring/mfa_disabled_for_gcp_user.yml
> +  raw_event_query: SELECT * FROM IAM WHERE $Action="UNENROLL_USER_FROM_STRONG_AUTH"
update sourcename in the raw_query as well and use new dql

2023-07-26 09:37 UTC, aman1808 commented on workbooks/Advanced Threat Detection/IAM Monitoring/mfa_disabled_for_gcp_user.yml
> +  DetectionScore: '5'
revisit the numbers on score, severity and confidence as this use case looks more serious

2023-07-26 09:37 UTC, aman1808 commented on workbooks/Basic Security Monitoring/Authentication Attacks/successfull_login_from_compromised_user.yml
> +  query: stream=authentication where action='LOGIN' and status='PASSED' | groupby
how do we know that the user is a compromised user, this does not seem to be a complete use case. please discuss this internally with @RoshanPoojari20

2023-07-26 09:37 UTC, aman1808 commented on workbooks/Basic Security Monitoring/Authentication Attacks/successfull_login_from_compromised_user.yml
> +  query: stream=authentication where action='LOGIN' and status='PASSED' | groupby
should ideally have a pre existing list of compromised users from a event store to confirm this.

2023-07-26 09:37 UTC, aman1808 commented on workbooks/Basic Security Monitoring/Authentication Attacks/successfull_login_from_compromised_user.yml
> +  DetectionScore: '5'
the score and severity needs to be more accurate, after validation of compromised user

2023-07-26 09:37 UTC, aman1808 commented on workbooks/Basic Security Monitoring/Authentication Attacks/successfull_login_from_compromised_user.yml
> +  raw_event_query: SELECT * FROM AUTHENTICATION WHERE $Action="LOGIN" AND $Status="PASSED"
use new dql here

2023-07-27 07:08 UTC, Avni3 commented on workbooks/Advanced Threat Detection/IAM Monitoring/mfa_disabled_for_gcp_user.yml
> +  query: stream=iam where action='UNENROLL_USER_FROM_STRONG_AUTH' | groupby user,
Added the sourcename in the query as G-SUITE and increased the limit to 100

2023-07-27 07:09 UTC, Avni3 commented on workbooks/Advanced Threat Detection/IAM Monitoring/mfa_disabled_for_gcp_user.yml
> +  raw_event_query: SELECT * FROM IAM WHERE $Action="UNENROLL_USER_FROM_STRONG_AUTH"
Updated the raw event query in new dql and added sourcename as G-SUITE

2023-07-27 07:10 UTC, Avni3 commented on workbooks/Advanced Threat Detection/IAM Monitoring/mfa_disabled_for_gcp_user.yml
> +  DetectionScore: '5'
Changed the DetectionScore, DetectionSeverity, DetectionConfidence in the usecase

2023-07-28 05:07 UTC, Avni3 commented on workbooks/Basic Security Monitoring/Authentication Attacks/successfull_login_from_compromised_user.yml
> +  query: stream=authentication where action='LOGIN' and status='PASSED' | groupby
Discussed with Roshan and added a second query which is responsible for checking if the target user value is present in the Compromised User list. Also, created a retrieve compromised user usecase to maintain a list of target user which are found to be compromised.

2023-07-28 05:09 UTC, Avni3 commented on workbooks/Basic Security Monitoring/Authentication Attacks/successfull_login_from_compromised_user.yml
> +  DetectionScore: '5'
Changed the DetectionScore, DetectionSeverity, and DetectionConfidence in the usecase.

2023-07-28 05:09 UTC, Avni3 commented on workbooks/Basic Security Monitoring/Authentication Attacks/successfull_login_from_compromised_user.yml
> +  raw_event_query: SELECT * FROM AUTHENTICATION WHERE $Action="LOGIN" AND $Status="PASSED"
Added New DQL in raw event query

2023-07-31 10:15 UTC, aman1808 approved these changes

2023-07-31 10:15 UTC, merged