DQL Updated for Proxy Monitoring
dnif/content pull request #205
Opened 2023-08-07 13:08 UTC by rakshitshetty22

We have Updated the Proxy Monitoring Usecases

2023-08-09 15:11 UTC, aman1808 requested changes

2023-08-09 15:11 UTC, aman1808 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/onedrive_browsing_traffic_profile_ff93ab00d61849eab1a018549edd42a6.yml
>    DetectionConfidence: Low
missing detection severity

2023-08-09 15:11 UTC, aman1808 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/solarwinds_backdoor_c2_host_name_detected_8800334c1d054398ae3f8cc46082f899.yml
> +description: ''
why is the description deleted?

2023-08-09 15:11 UTC, aman1808 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/telegram_api_access_fbf015539fa141d1bbe6c4695e17f152.yml
> +description: ''
desc deleted?

2023-08-09 15:11 UTC, aman1808 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/turla_comrat_malware_37f1c7de9f744ae2bf2f3397c4190548.yml
> +description: ''
desc deleted?

2023-08-09 15:11 UTC, aman1808 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/windows_powershell_user_agent_1b613f156eaf47ac8b9ad17d2ca842ba.yml
> +description: ''
add desc

2023-08-09 15:11 UTC, aman1808 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/windows_webdav_useragent_b9614c55a4d145f181ab386c936220f6.yml
> +description: ''
add desc

2023-08-09 15:12 UTC, aman1808 commented
@rakshitshetty22 @hemantvish97 Need to validate the detection score for all the use cases

2023-08-16 12:34 UTC, rakshitshetty22 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/empty_user_agent_3b63781a207d4d23b4a714bb31916505.yml
> +  query: stream=webfilter where useragent="" | groupby system, srcip, useragent
Done with the changes.

2023-08-16 12:35 UTC, rakshitshetty22 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/onedrive_browsing_traffic_profile_ff93ab00d61849eab1a018549edd42a6.yml
>    DetectionConfidence: Low
Updated the severity.

2023-08-16 12:35 UTC, rakshitshetty22 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/solarwinds_backdoor_c2_host_name_detected_8800334c1d054398ae3f8cc46082f899.yml
> +description: ''
Updated the Description.

2023-08-16 12:35 UTC, rakshitshetty22 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/suspicious_user_agent_e10722c6f4c4485f86b6c318a0b1788c.yml
> +description: ''
Updated the Description.

2023-08-16 12:35 UTC, rakshitshetty22 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/turla_comrat_malware_37f1c7de9f744ae2bf2f3397c4190548.yml
> +description: ''
Updated the Description.

2023-08-16 12:35 UTC, rakshitshetty22 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/windows_powershell_user_agent_1b613f156eaf47ac8b9ad17d2ca842ba.yml
> +description: ''
Updated the Description.

2023-08-16 12:35 UTC, rakshitshetty22 commented on workbooks/Advanced Threat Detection/Proxy Monitoring/windows_webdav_useragent_b9614c55a4d145f181ab386c936220f6.yml
> +description: ''
Updated the Description.

2023-08-28 08:20 UTC, aman1808 approved these changes

2023-08-28 08:21 UTC, merged