Updated_The_Authentication_Attacks_Workbooks
dnif/content pull request #206
Opened 2023-08-09 06:32 UTC by hemantvish97

Updated the Authentication Attacks Workbooks(15).

2023-08-14 14:01 UTC, aman1808 requested changes

2023-08-16 11:09 UTC, hemantvish97 commented on workbooks/Basic Security Monitoring/Authentication Attacks/abnormal_ssh_login_attempts_for_a_user_e192a064480b46f78350cc3fd080f910.yml
>    SuspectHost: $SrcIP
We have tested and found the output is "SrcIP" So, we have changed the value in the workbook as per the output.

2023-08-16 11:10 UTC, hemantvish97 commented on workbooks/Basic Security Monitoring/Authentication Attacks/abnormal_vpn_login_attempts_for_a_user_5e8246d661064bdb9e66e171773999db.yml
>    SuspectHost: $SrcIP
We have tested and found the output is "SrcIP" So, we have changed the value in the workbook as per the output.

2023-08-16 11:11 UTC, hemantvish97 commented on workbooks/Basic Security Monitoring/Authentication Attacks/login_failure_from_expired_account_80b3d7f21d66406dad433180349a3bca.yml
> +  query: 'stream=AUTHENTICATION where action=''LOGIN'' and status=''FAILED'' and reason=''ACCOUNT_EXPIRED''
Done with the changes

2023-08-16 11:11 UTC, hemantvish97 commented on workbooks/Basic Security Monitoring/Authentication Attacks/login_failure_from_expired_account_80b3d7f21d66406dad433180349a3bca.yml
> +  raw_event_query: 'stream=AUTHENTICATION where action=''LOGIN'' and status=''FAILED''
Done with the changes

2023-08-16 11:11 UTC, hemantvish97 commented on workbooks/Basic Security Monitoring/Authentication Attacks/multiple_successful_login_from_different_country_by_single_user_6d800284e91a479f92f4cb1e187294d6.yml
> +    CountSrcCN > 3
Done with the changes

2023-08-28 08:22 UTC, aman1808 approved these changes

2023-08-28 08:22 UTC, merged